name: innsouls_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_screenutil: ^5.9.3
  get_storage: ^2.1.1
  dio: ^5.7.0
  octo_image: ^2.1.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^5.0.0

flutter:
#  assets:
#    - assets/
#    - assets/images/
#    - assets/icons/
  assets:
    - assets/images/logos/
    - assets/images/
    - assets/images/logos/icons/
    - assets/images/banners/
    - assets/images/product/
    - assets/images/logos/payment/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/nunito_sans.ttf
          weight: 400
    - family: Raleway
      fonts:
        - asset: fonts/raleway.ttf
          weight: 400
  uses-material-design: true
